# If running locally, your Anthropic API key will be needed here.
# The Cloud Run deployed version will not look at this one. It will look at the one in terraform.tfvars.
# Or just leave blank to disable.
api_key: ""
model: claude-sonnet-4-5

types:
  - title: summary
    prompt: |
      The following is a transcript of a recorded 
      meeting combined with on-screen text. Create a summary of it.
    max_tokens: 2000
  - title: action_items
    prompt: |
      The following is a transcript of a recorded 
      meeting combined with on-screen text. Create a list of action items.
    max_tokens: 1000
  - title: topic
    prompt: |
      The following is a transcript of a recorded 
      meeting combined with on-screen text. Describe it in one topic sentence.
    max_tokens: 200