defaults:
  - db: localconn
  - cast: anthropic
  - _self_

server:
  auth:
    keys: []

ocr:
  model: easyocr # options: easyocr, lightonocr
  lang: [en]

transcript:
  model_size: turbo
  precision: int8
  batch_size: 8


cast: null
