# Once you deployed your cloud resources, to find your CloudSQL connection info, 
# go to the terraform directory and run:
#   terraform output
provider: cloudsql
user: mink-user
port: 5432
name: 
password: 
host: 